
# use mysql instead of h2
#spring.profiles.active: mysql

# show sql statements for mapper
logging.level.shuaicj.example.mybatis.relationship.mapper: DEBUG


---
spring.profiles: mysql
spring.datasource.url: jdbc:mysql://localhost/hellomybatis?useSSL=false&useUnicode=true&characterEncoding=utf8
spring.datasource.username: shuaicj
spring.datasource.password: shuaicj
