
# use mysql instead of h2
#spring.profiles.active: mysql

# define type alias package
#mybatis.typeAliasesPackage: shuaicj.example.mybatis.entity

# mapper locations, it's optional if the mapper class and the mapper xml are in the same package
#mybatis.mapperLocations: classpath*:/**/mapper/*.xml

# auto map the db column in underscore case to the java property in came case, it's optional here
# because we have defined the resultMap
#mybatis.configuration.mapUnderscoreToCamelCase: true

# use EnumOrdinalTypeHandler instead of EnumTypeHandler
mybatis.configuration.defaultEnumTypeHandler: org.apache.ibatis.type.EnumOrdinalTypeHandler

# show sql statements for mapper
logging.level.shuaicj.example.mybatis.mapper: DEBUG


---
spring.profiles: mysql
spring.datasource.url: jdbc:mysql://localhost/hellomybatis?useSSL=false&useUnicode=true&characterEncoding=utf8
spring.datasource.username: shuaicj
spring.datasource.password: shuaicj
